### PR TITLE
be clearer about export

### LINKED ISSUE #23: Tile policy: be clearer about export
The tile policy talks about "calls to /cgi-bin/export". There are two issues with that: 

1. It isn't clear from the name that the policy even applies to exports (and not, e.g., the API policy). Should the policy be called "Tile and map image policy" or something like that?
2. It appears that the current OSM web site uses paths like "http://www.openstreetmap.org/export/finish" that do not include the /cgi-bin/ component, hence users might be misled to thinking the policy does not apply to these URLs. Should we perhaps replace "Calls to /cgi-bin/export may only be triggered..." by "Image exports may only be triggered..."?

### PR DESCRIPTION
**Pull request by woodpeck**
Closes #23

### CODE REVIEW

**Comment by tomhughes** [comment]
I'm not sure I like either of these edits.

The map image export is a service provided by the tile servers and I think it just confuses things adding that to the title.

Mentioning the URL specifically makes it very clear what it is we don't want people to do and again changing that makes things less clear.

**Comment by woodpeck** [comment]
I understand. My suggestion came from this question here https://help.openstreetmap.org/questions/53853/cannot-get-mapnik-image-from-exportfinish-with-python where someone tried to automate the call on the main site and I told him that what he was doing was against the policy, but then noticed that the policy (in all its clarity) was not actually saying "don't do this".

**Comment by tomhughes** [comment]
Interesting that somebody was doing it that way. I wondered if anybody would try that when I blocked direct access to the CGI script but as that user discovered it doesn't work unless you really try hard.

**Comment by Firefishy** [comment]
Closing this because of age. Feel free to re-open if still relevent.

**Pull request closed without merging**
