### PR TITLE
Add section with links to servers status and statisticss.

### PR DESCRIPTION
**Pull request by mikelmaron**

### CODE REVIEW

**Comment by tomhughes** [comment]
The uptime page is also not very reliable because it requires manual tagging of the tests at statuscake to get them to show up.

**Comment by mikelmaron** [comment]
@Firefishy @tomhughes do you prefer I add short clarification to the wiki and uptime links? or remove the links?

**Comment by mmd-osm** [comment]
There’s really no community to update that wiki page, it’s more or less stale content these days. The last user updating it once in a while has been blocked indefinitely for otherwise unrelated reasons.

**Comment by mikelmaron** [comment]
@mmd-osm aside from this PR .. should we remove that table from the wiki page?

Stepping back, the reason I created this PR was because I was looking for server status information. I went to the wiki, as I expect many people do, and was confused by all the links and resources there. Seemed to me the OWG webpage would have a good clear link to resources.

So the link to hardware.openstreetmap.org seems enough for OWG site. uptime.openstreetmap.org also seems pretty useful for a quick and clear view of status. @tomhughes you say it's unreliable because it's an additional step to maintain configuration there? Would you be comfortable with keeping a link to it?

**Comment by tomhughes** [comment]
Well the fundamental problem is that you're looking for something that doesn't exist - a human readable summary of server status.

We have all sort of alerts but they generally go to people mailboxes not to web pages, and they tend not to be directly meaningful to anybody that doesn't understand the details of our infrastructure.

A status page suitable for end users pretty much has to be human curated and we don't have the resource to do that.

**Comment by mikelmaron** [comment]
Something is better than nothing. I think uptime.openstreetmap.org is pretty decent. For instance, if I got a report that email was not being received, I could check uptime.osm.org, and see if the service was down / had recovered. Could be better than bothering admins unnecessarily.

Remember I'm simply trying to add a bit of detail here to operations.openstreetmap.org. If someone ended up there, they're not quite human but already somewhat familiar with what's going on.

**Review by Firefishy — APPROVED** [review]

**Pull request merged**
