### PR TITLE
Prohibit automatically submitting website forms

### PR DESCRIPTION
**Pull request by pnorman**
Implements https://github.com/openstreetmap/operations/issues/859

Creating this for discussion at the next ops meeting before a vote.

### CODE REVIEW

**Comment by mmd-osm** [comment]
JOSM's OAuth Authorisation Wizard would no longer be permitted with this policy in place. Has this been considered in the discussion?

**Comment by tomhughes** [comment]
Well it's exactly the kind of thing we don't want to allow so in that sense yes, sure it has.

**Comment by mmd-osm** [comment]
The interesting side effect of this policy is that it would force JOSM to drop OAuth 1.0a support much earlier than originally planned. Only their new OAuth 2.0 implementation complies with this policy.

**Comment by tomhughes** [comment]
I thought the wizard was optional and that 1.0a could be configured in the intended way, without giving your password to JOSM?

**Comment by mmd-osm** [comment]
The [documentation](https://josm.openstreetmap.de/wiki/Help/Dialog/OAuthAuthorisationWizard) still talks about some semi-automated and manual auth mode, which bypasses the wizard.

In the newest version 18700, I can't find a way to bypass the fully automated mode. Not sure when they've removed the semi-automated and manual mode.

image

**Comment by tsmock** [comment]
> However, in the newest version 18700, I can't find a way to bypass the fully automated mode anymore. Not sure when they've removed the other two options.

I suspect you are logged in via OAuth 2.0. It looks like there is a bug whereby if you are logged in via OAuth 2.0, OAuth 1.0 thinks you are logged in.

Anyway, from a coding perspective, we (JOSM) would _probably_ want to drop OAuth 1.0 if we end up having to make changes around it. We added OAuth 2.0 support in r18678, and there haven't been any "breaking" bugs reported with respect to OAuth 2.0.

In addition, cgimap has an [issue](https://github.com/zerebubuth/openstreetmap-cgimap/issues/286) open for dropping OAuth 1.0 support in "Q4/23 or Q1/24". So I can figure that OAuth 1.0a has < 1 year to live, and I'd rather start removing OAuth 1.0 code from JOSM prior to the drop-dead date. We'd probably drop the ability to do new logins via OAuth 1.0 (probably when you make this change) and encourage migration to OAuth 2.0 first, and keep the ability to use existing OAuth 1.0 tokens around for awhile.

**Pull request merged**
